Issue273 testcase multizone office simple air
ibpsa/project1-boptest pull request #412
Opened 2022-04-01 19:19 UTC by dhblum

This is for #273.  In particular, it implements the test case.

@JavierArroyoBastida The detailed test case review process with @Mathadon has completed and I have prepared the test case for merging.  Do you mind briefly reviewing this though to make sure everything is in order?

2022-04-05 11:50 UTC, JavierArroyoBastida requested changes
Thanks a lot, @dhblum and @Mathadon for the continued efforts! 
It is looking good to me. I would just suggest to add this emulator to the [compare_references.py file](https://github.com/ibpsa/project1-boptest/blob/09e60d39d853fbf10df6673c8b023bbb7a6ea4e1/testing/compare_references.py#L126) with a few critical/representative variables of this model. I believe this is good practice for future revisions to check on potential reference changes.

2022-04-07 15:46 UTC, dhblum commented
@JavierArroyoBastida Thanks for the review!  ``compare_references.py`` updated in https://github.com/ibpsa/project1-boptest/pull/412/commits/aa5a1e3fd188c0a8580bae9e65373159d166a836.

2022-04-07 15:47 UTC, dhblum commented on data/find_days.py
> +    peak_cool_restriction_hour: integer, optional
I suggest waiting until needed.

2022-04-07 15:48 UTC, JavierArroyoBastida commented on data/find_days.py
> +    peak_cool_restriction_hour: integer, optional
Ok makes sense!

2022-04-07 15:49 UTC, JavierArroyoBastida commented
I see. Looking great, thanks! I'd suggest merging once tests pass.

2022-04-07 15:50 UTC, JavierArroyoBastida approved these changes

2022-04-07 20:39 UTC, merged