Issue73 messaging
ibpsa/project1-boptest pull request #436
Opened 2022-06-14 15:23 UTC by SenHuang19

2022-06-22 20:36 UTC, dhblum requested changes
@SenHuang19 Generally this is looking very good, thank you so much.  A few in-line comments though I'm hoping you can address which I've marked up.

2022-06-22 20:36 UTC, dhblum commented on testcase.py
> +        interval: float
@SenHuang19 A reason to change interval and horizon to float instead of int?  I think it may be safer to use int?

2022-06-22 20:36 UTC, dhblum commented on testcase.py
> +        warmup_period: float
@SenHuang19 A reason to change warmup_period and start_time to float instead of int?  I think it may be safer to use int?

2022-06-22 20:36 UTC, dhblum commented on testcase.py
> +            message = "parameter 'step' must be an integral number but is {}".format(type(step))
@SenHuang19 Change "integral" to "integer"

2022-06-22 20:36 UTC, dhblum commented on testcase.py
>                  message = "Failed to advance simulation: {}"
@SenHuang19 I think this needs a .format(res) at the end so the full error message is returned, just like it is logged in Line 306?

2022-06-22 20:38 UTC, dhblum commented on testcase.py
> +                                alert_message = alert_message +'; '+ message
Also in this case, please log as logger.warning.

2022-06-25 00:36 UTC, SenHuang19 commented
@dhblum As per our earlier discussion, we added more unit tests and made floats to be acceptable for the time-related parameters. However, the unit test fails for the new commit. I spent some times on this and realized the issue is that
the changes I added to the resapi.py,

    elif '_u' in key:
        parser_advance.add_argument(key, type=float)

yields different results as

    value = float(u[key])

As an example, the former generates results like 

    -11.1297454685654

while the latter generates results like
 
    -11.1297454685655

So we either need to update the reference dataset or come out a better way to handle the decimals.

Let me know your thoughts and we can chat about it in Toronto

2022-06-25 00:44 UTC, dhblum commented
Thanks a lot @SenHuang19 for the update.  The difference in the results you show are extremely small numeric differences and not perceivable to humans.  I don't mind updating the reference results to have the implementation we prefer.

I will take a quick look, but my plan is to merge your changes and apply additional updates and clean ups as we discussed.  I'll take care of. updating reference results accordingly.  I'll ping you when you can have a final review and/or if more discussion is needed. Thanks again!

2022-06-25 21:15 UTC, dhblum approved these changes
Thanks for the changes.  Will merge as is.

2022-06-25 21:15 UTC, merged