Issue464 move io html
ibpsa/project1-boptest pull request #468
Opened 2022-08-05 15:11 UTC by EttoreZ

This pull request is for issue #464

2022-08-05 18:26 UTC, dhblum requested changes
Thanks @EttoreZ.  In addition to my inline comments: 

- Please also add a line to the ``releasenotes.md`` under the heading for a backwards compatible change that does not impact benchmark results.  Add the heading if it does not already exist to the xx/xx/xxxx release section (top) and you can look to previous releases for guidance on what to write and how to format, etc.
- Add your name to ``contributors.md`` if it doesn't exist already.

2022-08-05 18:26 UTC, dhblum commented on data/README.md
> +## Testcase I/O generation for documentation
Suggest "Generate Documentation for Test Case I/O Points"

2022-08-05 18:26 UTC, dhblum commented on data/README.md
> +"inputs.txt": html code documenting the inputs
Make into bullet point list so renders correctly on github page

2022-08-05 18:26 UTC, dhblum commented on data/README.md
> +"measurements.txt": html code documenting the outputs
Add also some brief instructions on how to use.  For instance that you should first deploy the test case of interest and then run this script with python, maybe just showing the cmd line command.

2022-08-08 16:29 UTC, dhblum commented
@EttoreZ just for your information I merged https://github.com/ibpsa/project1-boptest/pull/467.

2022-08-09 03:13 UTC, EttoreZ commented
> @EttoreZ just for your information I merged #467.

Thank you for the heads up @dhblum. I updated the pull request with the suggested changes.

2022-08-10 14:49 UTC, dhblum commented on data/README.md
> +``$ TESTCASE=<testcase_name> docker-compose up``. Then open a terminal in
@EttoreZ Just documenting what we discussed, please remove this command for deploying test case and refer to root readme so as not to duplicate.

2022-08-10 15:01 UTC, dhblum requested changes
Thanks @EttoreZ for the updates.  Please just address the one additional inline comment and then I think this will be ready to go.

2022-08-10 15:31 UTC, EttoreZ commented
Thanks for the careful review @dhblum. I addressed the last comments and updated the PR

2022-08-10 16:41 UTC, merged