Issue680 update dependency bestest hydronic
ibpsa/project1-boptest pull request #681
Opened 2024-09-13 23:31 UTC by EttoreZ

This pull request is for #680. Modelica code of `BETEST_hydronic` and `BESTEST_hydronic_heat_pump` was updated to NOT extend from model of IDEAS library, but instead duplicate it, to make test case Modelica code maintenance easier.

2024-09-14 01:21 UTC, EttoreZ commented
One comment. I did not add the new `wrapped.fmu` since the code change does not affect results. This is to avoid further increasing the size repository.

2024-10-15 19:42 UTC, dhblum commented
@jelgerjansen This PR proposes to move the code for the ``bestest_hydronic`` and ``bestest_hydronic_heat_pump`` test cases from IDEAS (and included in BOPTEST via Modelica ``extends``), to having the models in the IBPSA repo and have IDEAS as a versioned dependency.  This is the approach taken with other test cases in BOPTEST that depend on IDEAS and Buildings.  We feel this would help decouple maintenance and future development of the models from IDEAS development and maintenance, especially for things that are not IDEAS-specific.  A downside is that the test cases are no longer unit tested with your IDEAS development.  

Let me know if this seems ok to you or if you see reasons we should keep the models within IDEAS, as was set up originally.

Note also that since the model code would be duplicated from and original distribution in IDEAS, I've included reference to the IDEAS license in the BOPTEST license as part of this PR.

2024-10-17 15:40 UTC, jelgerjansen commented
Hi @dhblum, I think it is OK to move these models from IDEAS to BOPTEST. According to my knowledge, the main functionalities of both the component models in both models are also tested in other unit tests. Or do I miss something important here @Mathadon?

I noticed that the IDEAS v2.2.1 is referred to, but this was before the update of MSL to v4.0.0. Are you sure about the IDEAS version in the documentation?

2024-10-17 15:48 UTC, EttoreZ commented
hey @jelgerjansen answering your second question. This version of the test case still uses Modelica 3.2.3 due to the legacy support of JModelica for compilation, hence IDEAS 2.2.1. We are moving away from JModelica and working to update all BOPTEST test cases to Modelica 4.0 and related version of the libraries (like IDEAS 3.0.0).

2024-10-17 16:12 UTC, dhblum commented
Thanks @jelgerjansen.  To your first question about unit tests: BOPTEST unit tests test the compilation and simulation of the full test case models with reference results produced and compared for BOPTEST KPI values and a selection of variable timeseries that are generated during the tests.  I imagine the components of the models are unit tested in the IDEAS library, but you or @Mathadon may be able to confirm better.

2024-10-18 12:13 UTC, jelgerjansen commented
@EttoreZ @dhblum thanks for the clarification :) 
Please proceed with this PR, and we'll check internally if we keep the models in IDEAS, move them to an Obsolete package, or remove them.

2024-10-18 13:44 UTC, dhblum commented
Thank you both @jelgerjansen and @Mathadon.  We will proceed with this PR.

2024-10-18 14:01 UTC, dhblum requested changes
@EttoreZ Please address my two comments.

2024-10-18 15:42 UTC, dhblum commented
@EttoreZ Can you also address https://github.com/ibpsa/project1-boptest/issues/625 in this PR?

2024-10-18 17:47 UTC, EttoreZ commented
> @EttoreZ Can you also address #625 in this PR?

Hey @dhblum I gave it a bit more thought. I think it makes more sense to integrate #625 with the min max PR for #658, since I am already updating the inputs for `BETEST_hydronic` and `BESTEST_hydronic_heat_pump` there, and it would be easier to merge them without conflicts. Is that ok?

2024-10-18 17:48 UTC, dhblum commented
@EttoreZ Yes, that sounds fine.  Thanks for thinking strategically about it.  Then just let me know if/when this PR is ready.

2024-10-18 17:51 UTC, EttoreZ commented
Ok perfect, @dhblum PR should be ready now and I will work on the min max PR.

2024-10-18 18:18 UTC, dhblum commented on testcases/bestest_hydronic_heat_pump/models/BESTESTHydronicHeatPump/TestCase.mo
> +</html>", revisions="<html>
Resolved in https://github.com/ibpsa/project1-boptest/pull/681/commits/a7cea379e586967d6f513ab29e2c6abd1b99f1d4.

2024-10-18 18:18 UTC, dhblum commented on testcases/bestest_hydronic/models/BESTESTHydronic/TestCase.mo
> +</html>", revisions="<html>
Resolved in https://github.com/ibpsa/project1-boptest/pull/681/commits/a7cea379e586967d6f513ab29e2c6abd1b99f1d4.

2024-10-19 03:11 UTC, merged