Issue639 actuator travel
ibpsa/project1-boptest pull request #699
Opened 2024-11-01 02:55 UTC by terrancelu92

@dhblum, I have mainly uploaded the KPI code associated with the existing test cases. Additionally, I’ve included the content we discussed for both the existing and new test cases.   [testcase_kpi.py](https://github.com/ibpsa/project1-boptest/compare/issue639_actuatorTravel...terrancelu92:project1-boptest:issue639_actuatorTravel?expand=1#diff-b09d4fcd47f1926c0c538726ad9ae5a669955b1926d5894157598e23cdb79b0c) is a simple demonstration example.
Once we agree on the existing test cases, I will push the codse for the new test cases (for which I have already implemented a draft). The [kpi_calculator.py](https://github.com/ibpsa/project1-boptest/compare/issue639_actuatorTravel...terrancelu92:project1-boptest:issue639_actuatorTravel?expand=1#diff-e6ba06136124ecf3cf7147b803747f09ad84e9fb213eb04b7e16deeb3bccc86d) contains some components related to the new test case, but I have not yet pushed the workflow for actuator tagging, including the parsing code and overwritten model block, for the new test case.

Thank you!

-------------------------------------
- For existing testcases
  
  - Calculation method for the KPI where we:
	  - First scale both the x and y axis data to between 0 and 1 (y-axis based on the allowable range of the control signal indicated by BOPTEST, x-axis based on time period under analysis), 
	  - Then calculate the arc length and NOT do any additional normalization to a straight line (which would be equal to 1 anyway in this case), 
	  - And then average it over total number of signals (as we do now).
  - add normalization by number of actuators to kpi_calc and documentation (and sum to doc)
  - add config file to kpi directory specifying map for variables in existing test cases and use in kpi_calculator for these cases
  - add comments to kpi calc code 

- New testcase (add workflow for actuator tagging)
    -  update overwrite block in IBPSA Modelica Library
    -  update parser for pulling from model and adding to kpi.json
    -  update kpi_calculator pulling from kpi.json

2025-09-25 15:42 UTC, dhblum requested changes
Thank you @terrancelu92 for this implementation.  Generally, from structure and function points of view, it's looking good.  However, please address the inline comments I made to mainly improve consistency with other code and clarity of implementation.  

Also, regarding the changes to the signal exchange block Modelica code, note the following:

- Changes will ultimately need to be made in the Modelica IBPSA Library (not the IDEAS library as you've forked), so that they flow down into all libaries that extend from it, including IDEAS and Buildings.
- For SignalsForActuatorTravel.mo, I suggest using "Other" instead of "Others".  Minor english preference.
- For Read.mo, I suggest the new parameter be defined as follows (note consistency with existing parameter "zone"): 
```  
parameter SignalTypes.SignalsForActuatorTravel actuatorType = SignalTypes.SignalsForActuatorTravel.None if (KPIs==IDEAS.Utilities.IO.SignalExchange.SignalTypes.SignalsForKPIs.ActuatorTravel)
"Actuator type designation, required if KPIs is ActuatorTravel"
annotation(Dialog(enable=(KPIs==IDEAS.Utilities.IO.SignalExchange.SignalTypes.SignalsForKPIs.ActuatorTravel)));
```

2025-09-25 15:42 UTC, dhblum commented on docs/design/source/core_kpi.rst
> +   is turned on and off. This measure is important to assess the wear and
Since displacement is more than just on/off cycles, I'd suggest not limiting the description to on and off.  Maybe something more generic like "The actuator travel measures the amount of movement experienced by the actuators in the HVAC system.  This measure is important..."

2025-09-25 15:42 UTC, dhblum commented on docs/design/source/core_kpi.rst
> +
This is the actuator travel for one actuator.  Please add description and equation for the final KPI value calculation, which is the average of all actuators.

2025-09-25 15:42 UTC, dhblum commented on parsing/parser.py
> +            if signal_type == 'ControlActuatorTravel':
Recommend string to just be "ActuatorTravel" as "Actuator" is sufficient to describe the physical device and adding "Control" could add confusion as to what is meant.  I recognize this means changing references elsewhere, including in the signal exchange block modelica code.

2025-09-25 15:42 UTC, dhblum commented on parsing/parser.py
> +                signal_type = 'ControlActuator[{0}]'.format(__cat_map.get(__cat_val, str(__cat_val)))
I think the signal type string here ('ControlActuator') should be the same as that defined in 287 to be consistent with the pattern for other KPI types and to make it easier to follow.

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +        return self.ltra_tot/len(self.ltra_dict)
Better to return ``self.ltra_tot`` rather than re-calculate so as to only make the calculation in one place.  Follow similar pattern as other KPIs, e.g. Line 594 for cost.  Also, related to my comment above, ``self.ltra_tot`` should represent the final KPI and not have to be adjusted further upon return.

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +        self.case.ltra_tot            = self.ltra_tot/len(self.ltra_dict) #Divide by the number of the control actuators
Suggest following the same pattern as other KPIs for consistency in normalization.  See line 584 for energy cost, where the division by floor area happens when calculating the total on the fly.  I suggest similar here: move the ``/len(self.ltra_dict)`` to line 695.

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +        self.ltra_tot = 0.
Add space between end of docstring and start of code (consider where needed elsewhere too).  A code format I'd like to keep consistent.

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +        '''This method returns the measure of the actuator travel displacement when accounting for the sum of all
Should this be "average of all" instead of "sum of all"?

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +        return float(value)
Add space before return and space between docstring and start of code.  Conventions I'd like to keep consistent throughout.

2025-09-25 15:42 UTC, dhblum commented on kpis/kpi_calculator.py
> +
Remove spaces between parameters.  A convention I'd like to keep consistent.

2025-09-25 15:42 UTC, dhblum commented on docs/design/source/core_kpi.rst
> +   We propose using displacement, which measures the total distance the actuator travels
Suggest revision to be definitive as "We use displacement, which ..."

2025-09-29 01:23 UTC, xinglu-pnnl commented on docs/design/source/core_kpi.rst
> +   is turned on and off. This measure is important to assess the wear and
Change to "The actuator travel quantifies the overall movement of HVAC system actuators. This measure is important"

2025-09-29 01:26 UTC, terrancelu92 commented on docs/design/source/core_kpi.rst
> +
Added

2025-09-29 01:27 UTC, xinglu-pnnl commented on parsing/parser.py
> +            if signal_type == 'ControlActuatorTravel':
Change all the related codes/terms to ""ActuatorTravel"

2025-09-29 01:27 UTC, terrancelu92 commented on parsing/parser.py
> +                signal_type = 'ControlActuator[{0}]'.format(__cat_map.get(__cat_val, str(__cat_val)))
Change all the related codes/terms to ""ActuatorTravel"

2025-09-29 01:28 UTC, terrancelu92 commented on kpis/kpi_calculator.py
> +        return self.ltra_tot/len(self.ltra_dict)
Revise to the form as other KPIs

2025-09-29 01:30 UTC, xinglu-pnnl commented on kpis/kpi_calculator.py
> +        self.case.ltra_tot            = self.ltra_tot/len(self.ltra_dict) #Divide by the number of the control actuators
Revise to the form as other KPIs (See latest line 678)

2025-09-29 01:30 UTC, xinglu-pnnl commented on kpis/kpi_calculator.py
> +        self.ltra_tot = 0.
Added the space and checked the similar issue.

2025-09-29 01:31 UTC, xinglu-pnnl commented on kpis/kpi_calculator.py
> +        '''This method returns the measure of the actuator travel displacement when accounting for the sum of all
Corrected

2025-09-29 01:31 UTC, terrancelu92 commented on kpis/kpi_calculator.py
> +        return float(value)
Added the space and checked the other lines.

2025-09-29 01:32 UTC, terrancelu92 commented on kpis/kpi_calculator.py
> +
Removed spaces and checked the other lines

2025-09-29 01:32 UTC, xinglu-pnnl commented on docs/design/source/core_kpi.rst
> +   We propose using displacement, which measures the total distance the actuator travels
Updated

2025-09-29 14:38 UTC, dhblum approved these changes
Thank you @terrancelu92 for the corrections.  This PR is ready to merge to the staging branch.  Adding that this is reference to #639.

2025-09-29 14:38 UTC, merged