Singlezone commercial hydronic adrenalin
ibpsa/project1-boptest pull request #703
Opened 2024-11-12 01:27 UTC by EttoreZ

This PR is to address #702 to merge Adrenalin changes to `single_zone_commercial_hydronic` model.

2024-11-25 14:28 UTC, dhblum commented
@EttoreZ @HWalnum Can you state if this is ready for review and finalization, or if there's still more work to be done on this one?

2024-11-25 17:01 UTC, EttoreZ commented
@HWalnum correct me if I am wrong, the documentation still needs to be updated and then it is ready review, right?

2024-11-26 07:50 UTC, HWalnum commented
@EttoreZ. Yes, that is correct. I will try to have a look at it this week

2024-12-01 20:36 UTC, HWalnum commented
@EttoreZ I have updated the documentation.

2025-01-07 18:36 UTC, dhblum requested changes
@HWalnum Can you address the one inline comment and also provide a comment to this PR that summarizes the changes made in this PR?  Something in bullet form might be best.

2025-01-07 18:36 UTC, dhblum commented on testcases/singlezone_commercial_hydronic/models/OU44Emulator/Documentation.mo
> +Updated model according to Adrenalin changes.
Add reference to BOPTEST issue number.

2025-02-07 16:19 UTC, dhblum requested changes
@HWalnum I had a closer look at this.  Can you address my inline comments and make any appropriate changes?  Don't commit and push a new version of the FMU yet, until any changes in the model are settled. 

Can you also add a line in the ``releasenotes.md``?

Once changes in the model are settled, I can update unit test results, the wrapped FMU, and finalize things.

2025-02-11 19:50 UTC, HWalnum commented on testcases/singlezone_commercial_hydronic/models/OU44Emulator/Documentation.mo
> +        <code>ahu_reaTCoiSup_y</code> [K] [min=None, max=None]: AHU heating coil supply water temperature
agree

2025-02-11 19:54 UTC, HWalnum commented on testcases/singlezone_commercial_hydronic/models/OU44Emulator/Models/BuildingBase.mo
> +  Buildings.Fluid.FixedResistances.PressureDrop res(
This is called a "bleeder" and is a heating coil protection system, typically used in cold climates (at least in Norway). Normally you use a small throttling valve (DN10 or DN15). The idea is that if AHU is located far from the hydronic heating system distribution manifold, this ensures that you always have hot water available, in case the rotating HX fails. If not, you might risk that the water in the heating coil freezes.

2025-02-11 19:55 UTC, HWalnum commented on testcases/singlezone_commercial_hydronic/models/OU44Emulator/Documentation.mo
> +<p>Figure 2 shows the fan characteristics. The grey line shows the operational point at nominal speed.</p>
yes

2025-02-11 19:55 UTC, HWalnum commented on testcases/singlezone_commercial_hydronic/models/OU44Emulator/Documentation.mo
> +        <code>reaPFan_y</code> [W] [min=None, max=None]: Electrical power consumption of AHU supply and return fans
yes, I can do that

2025-02-11 20:46 UTC, HWalnum commented
@dhblum I responded to your comments and made changes. I also added something to the release notes, but was unsure of the desired level of detail.

2025-02-12 22:39 UTC, dhblum commented
Thanks @HWalnum.  I'm going to merge this PR and do some clean up plus unit test updates on the development branch before opening a new PR to master.  I'll come back to you if needed.

2025-02-12 22:39 UTC, dhblum approved these changes

2025-02-12 22:40 UTC, merged