Issue582 Update testcase1 and testcase 3 documentation
ibpsa/project1-boptest pull request #706
Opened 2024-11-15 11:03 UTC by Jaap-Neven

Written basic documentation of the layout of testcase 1 and testcase 3. Included resources to produce a pdf from latex and the most recent pdf version as well.

Did not refactor the names of the basic p-controllers in the example [controllers directory](https://github.com/ibpsa/project1-boptest/tree/de089cb310953a989c32f0c19f66317863a563c3/examples/python/controllers) and corresponding references yet. Should this be done or unnecessary?

2024-12-04 15:43 UTC, dhblum commented
This is for https://github.com/ibpsa/project1-boptest/issues/582.

@Jaap-Neven Thanks for the PR!  A couple comments and requests:

1. Instead of latex, pdf, and all the build files, can you provide the documentation of the test cases similarly to the other test cases and as defined in the design spec (see [here](https://ibpsa.github.io/project1-boptest/docs-design/testcasedev.html#documentation))?  That is, add the documentation as an html annotation in the Modelica model (for example see for the bestest_air case [here](https://github.com/ibpsa/project1-boptest/tree/master/testcases/bestest_air/models/BESTESTAir/TestCases/TestCase_Ideal.mo#L29)) and also copy to a ``/testcases/<test_case_name>/doc/index.html``, with any figures in a ``/testcases/<test_case_name>/doc/images/`` directory.  I suggest looking at the other test cases for templates (again see for example the bestest_air case [here](https://github.com/ibpsa/project1-boptest/tree/master/testcases/bestest_air/doc)).  This will align the docs with how things are done in other test cases, and also avoid needing to build, add, and use pdfs in git.
2. One of the things mentioned in #582 was the heater should be considered as a heater/cooler.  Therefore, can you change the measurement variable ``PHea_y`` to ``PHeaCoo_y``?  That will require a change in the Modelica model overwrite block, cascade into needing to update unit test results with the new variable, reflected in documentation, and maybe updates to the scripts in ``/examples``.

2024-12-04 15:43 UTC, dhblum requested changes
See previous comment for review requests.

2024-12-04 15:57 UTC, Jaap-Neven commented
Hi @dhblum, thanks for the feedback! I'll implement the requested changes at my earliest convenience.

2025-04-08 09:36 UTC, Jaap-Neven commented
New FMUs are compiled and all is ready for review

2025-04-25 20:38 UTC, dhblum commented
Thanks @Jaap-Neven.  I will merge this to a develop branch and take from here to merge to master.  I'll let you know if anything else is needed from you.

2025-04-25 20:39 UTC, merged